"use client";

import dynamic from "next/dynamic";
import { motion } from "framer-motion";
import { AlertTriangle, Globe2, Radar, TrendingUp } from "lucide-react";
import { Card } from "@/components/ui/Card";
import { Badge } from "@/components/ui/Badge";
import {
  CrossPlatformHop,
  GlobalIntelligenceSnapshot,
  IntelligenceAlert,
  IntelligenceFeedItem,
  IntelligenceLineageStep
} from "@/lib/types";
import { GlobalHeatmap } from "@/components/dashboard/GlobalHeatmap";
import { MisinformationNetworkGraph } from "@/components/dashboard/MisinformationNetworkGraph";
import { ContentLineageTracker } from "@/components/dashboard/ContentLineageTracker";
import { RealtimeTrustFeed } from "@/components/dashboard/RealtimeTrustFeed";
import { ClientDateText } from "@/components/ui/ClientDateText";

const LineChartComponent = dynamic(() => import("@/components/charts/LineChartComponent").then((mod) => mod.LineChartComponent), { ssr: false });
const BarChartComponent = dynamic(() => import("@/components/charts/BarChartComponent").then((mod) => mod.BarChartComponent), { ssr: false });

function IntelligenceAlertsPanel({ alerts }: { alerts: IntelligenceAlert[] }) {
  return (
    <Card>
      <div className="mb-4 flex items-center justify-between">
        <div>
          <p className="text-lg font-semibold text-white">Intelligence Alerts</p>
          <p className="text-sm text-slate-400">High-priority warnings generated by the GMIE layer.</p>
        </div>
        <Badge tone={alerts.some((alert) => alert.severity === "high") ? "danger" : "warning"}>{alerts.length} active</Badge>
      </div>
      <div className="space-y-3">
        {alerts.map((alert) => (
          <motion.div
            key={alert.id}
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            className="rounded-xl border border-white/10 bg-white/[0.03] px-4 py-4"
          >
            <div className="flex items-start justify-between gap-3">
              <div>
                <p className="text-sm font-medium text-white">{alert.title}</p>
                <p className="mt-2 text-sm leading-6 text-slate-300">{alert.detail}</p>
              </div>
              <Badge tone={alert.severity === "high" ? "danger" : alert.severity === "medium" ? "warning" : "info"}>{alert.severity}</Badge>
            </div>
          </motion.div>
        ))}
      </div>
    </Card>
  );
}

function CrossPlatformTracker({ hops }: { hops: CrossPlatformHop[] }) {
  return (
    <Card>
      <div className="mb-5">
        <p className="text-lg font-semibold text-white">Cross-Platform Tracking</p>
        <p className="text-sm text-slate-400">Simulated spread path showing how suspicious content travels between platforms.</p>
      </div>
      <div className="grid gap-3 sm:grid-cols-4">
        {hops.map((hop, index) => (
          <div key={`${hop.platform}-${hop.timestamp}`} className="relative rounded-xl border border-white/10 bg-white/[0.03] p-4">
            {index < hops.length - 1 ? <div className="absolute left-full top-1/2 hidden h-px w-6 -translate-y-1/2 bg-gradient-to-r from-cyan-400/50 to-transparent sm:block" /> : null}
            <p className="text-xs uppercase tracking-[0.2em] text-slate-500">{hop.platform}</p>
            <p className="mt-3 text-lg font-semibold capitalize text-white">{hop.status}</p>
            <ClientDateText value={hop.timestamp} mode="time" fallbackLabel={hop.timestamp.slice(11, 16)} className="mt-2 text-xs text-slate-400" />
          </div>
        ))}
      </div>
    </Card>
  );
}

function PredictiveEngineCard({
  prediction,
  topics
}: {
  prediction: GlobalIntelligenceSnapshot["prediction"];
  topics: string[];
}) {
  return (
    <Card>
      <div className="mb-5 flex items-center justify-between">
        <div>
          <p className="text-lg font-semibold text-white">Predictive Misinformation Engine</p>
          <p className="text-sm text-slate-400">Forecasting the probability that this narrative becomes a viral fake.</p>
        </div>
        <Badge tone={prediction.score > 70 ? "danger" : prediction.score > 45 ? "warning" : "info"}>{prediction.confidence}% confidence</Badge>
      </div>
      <div className="rounded-xl border border-white/10 bg-gradient-to-br from-rose-400/10 via-violet-400/8 to-cyan-400/8 p-5">
        <p className="text-xs uppercase tracking-[0.22em] text-slate-400">Prediction</p>
        <p className="mt-3 text-3xl font-semibold text-white">{prediction.label}</p>
        <p className="mt-3 text-sm leading-7 text-slate-300">{prediction.rationale}</p>
      </div>
      <div className="mt-4 flex flex-wrap gap-2">
        {topics.slice(0, 4).map((topic) => (
          <span key={topic} className="rounded-full border border-cyan-400/15 bg-cyan-400/8 px-3 py-1 text-xs text-cyan-100">
            {topic}
          </span>
        ))}
      </div>
    </Card>
  );
}

export function GlobalIntelligenceSection({ intelligence }: { intelligence: GlobalIntelligenceSnapshot }) {
  const lineData = intelligence.riskIndex.riskTrend;
  const distributionData = intelligence.riskIndex.distribution;

  return (
    <div className="space-y-6">
      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        {[
          {
            label: "Global Risk Score",
            value: `${intelligence.riskIndex.globalRiskScore}%`,
            detail: "Combined misinformation pressure across monitored regions.",
            icon: Globe2,
            accent: "from-cyan-400/16 to-blue-500/8"
          },
          {
            label: "Top Risk Region",
            value: intelligence.riskIndex.topRiskRegions[0]?.region || "Cross-platform",
            detail: `${intelligence.riskIndex.topRiskRegions[0]?.score || 0}% active intensity`,
            icon: Radar,
            accent: "from-rose-400/14 to-orange-500/8"
          },
          {
            label: "Trending Fake Topics",
            value: `${intelligence.riskIndex.trendingFakeTopics.length}`,
            detail: "Narrative patterns active inside monitored clusters.",
            icon: TrendingUp,
            accent: "from-violet-400/14 to-fuchsia-500/8"
          },
          {
            label: "High-Risk Creators",
            value: `${intelligence.riskIndex.highRiskCreators.length}`,
            detail: "Creator identities requiring additional scrutiny.",
            icon: AlertTriangle,
            accent: "from-amber-300/14 to-orange-500/8"
          }
        ].map((item) => {
          const Icon = item.icon;
          return (
            <Card key={item.label} className={`bg-gradient-to-br ${item.accent}`}>
              <div className="flex items-start justify-between gap-3">
                <div>
                  <p className="text-xs uppercase tracking-[0.2em] text-slate-400">{item.label}</p>
                  <p className="mt-3 text-3xl font-semibold text-white">{item.value}</p>
                  <p className="mt-2 text-sm text-slate-300">{item.detail}</p>
                </div>
                <div className="flex h-10 w-10 items-center justify-center rounded-lg border border-white/10 bg-white/8 text-cyan-100">
                  <Icon size={18} />
                </div>
              </div>
            </Card>
          );
        })}
      </div>

      <div className="grid gap-6 xl:grid-cols-[1.05fr,0.95fr]">
        <GlobalHeatmap regions={intelligence.regions} />
        <MisinformationNetworkGraph nodes={intelligence.network.nodes} edges={intelligence.network.edges} />
      </div>

      <div className="grid gap-6 xl:grid-cols-[1.02fr,0.98fr]">
        <Card>
          <div className="mb-4 flex items-center justify-between">
            <div>
              <p className="text-lg font-semibold text-white">Global Risk Index</p>
              <p className="text-sm text-slate-400">Trendline and distribution view for current misinformation pressure.</p>
            </div>
            <Badge tone="info">Live simulation</Badge>
          </div>
          <div className="grid gap-4 xl:grid-cols-2">
            <div className="h-72 rounded-xl border border-white/10 bg-slate-950/30 p-3">
              <LineChartComponent data={lineData} xKey="label" yKey="score" />
            </div>
            <div className="h-72 rounded-xl border border-white/10 bg-slate-950/30 p-3">
              <BarChartComponent data={distributionData} xKey="name" yKey="value" colors={["#F43F5E", "#FACC15", "#22C55E"]} />
            </div>
          </div>
        </Card>
        <PredictiveEngineCard prediction={intelligence.prediction} topics={intelligence.riskIndex.trendingFakeTopics} />
      </div>

      <div className="grid gap-6 xl:grid-cols-[1fr,1fr]">
        <ContentLineageTracker lineage={intelligence.lineage.map((item: IntelligenceLineageStep) => ({ stage: item.stage, label: item.label }))} />
        <CrossPlatformTracker hops={intelligence.crossPlatform} />
      </div>

      <div className="grid gap-6 xl:grid-cols-[1fr,1fr]">
        <RealtimeTrustFeed items={intelligence.feed as IntelligenceFeedItem[]} />
        <IntelligenceAlertsPanel alerts={intelligence.alerts} />
      </div>
    </div>
  );
}
